name: Sentinel
main: dev.war.sentinel.Sentinel
version: ${version}
api-version: ${apiVersion}
commands:
  login:
    aliases: [l]
    description: Logs in with the registered password
    usage: /login <password>
    permission: sentinel.login

  register:
    aliases: [r]
    description: Registers a new account
    usage: /register <password>
    permission: sentinel.register

  changepassword:
    description: Changes your account password
    usage: /changepassword <oldPassword> <newPassword>
    permission: sentinel.changepassword

  unregister:
    description: Deletes an existing account
    usage: /unregister <player>
    permission: sentinel.unregister

  sentinel:
    description: Plugin's main command
    usage: /sentinel
    permission: sentinel.use

permissions:
  sentinel.use:
    description: Allows use of the main Sentinel command
    default: op

  sentinel.login:
    description: Allows player to log in
    default: true

  sentinel.register:
    description: Allows player to register
    default: true

  sentinel.changepassword:
    description: Allows player to change their password
    default: true

  sentinel.unregister:
    description: Allows admin to unregister accounts
    default: op
